export const CREATE_COMPLAINT_REQUEST = 'CREATE_COMPLAINT_REQUEST'
export const CREATE_COMPLAINT_FAIL = 'CREATE_COMPLAINT_FAIL'
export const CREATE_COMPLAINT_SUCCESS = 'CREATE_COMPLAINT_SUCCESS'

export const GET_COMPLAINTS_REQUEST = 'GET_COMPLAINTS_REQUEST'
export const GET_COMPLAINTS_SUCCESS = 'GET_COMPLAINTS_SUCCESS'
export const GET_COMPLAINTS_FAIL = 'GET_COMPLAINTS_FAIL'

export const DELETE_COMPLAINT_REQUEST = 'DELETE_COMPLAINT_REQUEST'
export const DELETE_COMPLAINT_FAIL = 'DELETE_COMPLAINT_FAIL'
export const DELETE_COMPLAINT_SUCCESS = 'DELETE_COMPLAINT_SUCCESS'